name: cron

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: trainer
        run: curl --show-error "https://voice-chain.vercel.app/api/cron/checkTrainer"
      - name: transaction
        run: curl --show-error "https://voice-chain.vercel.app/api/cron/checkTransaction"
